#!/bin/sh
set -e
. pkg-mirror.conf

if ! which jq >/dev/null; then
    echo "jq not found"
    exit 1
fi

if ! which fetch >/dev/null; then
    echo "fetch not found"
    exit 1
fi

mkdir -p "${DIR}"

log() {
    echo "$(date) - ${1}" >>"${LOG_FILE}"
}

error() {
    log "Error: ${1}"
    exit 1
}

case "${1}" in
clean)
    rm -r "${DIR}"
    log "Cleaned directory ${DIR}"
    ;;
auto)
    mkdir -p "${DIR}/meta"
    mkdir -p "${DIR}/packages/All"
    /usr/bin/fetch "${URL}/packagesite.txz" -o "${DIR}/meta" || error "Failed to download packagesite.txz"
    tar xzf "${DIR}/meta/packagesite.txz" -C "${DIR}/meta/" || error "Failed to extract packagesite.txz"
    cat "${DIR}/meta/packagesite.yaml" | jq -r .\|.repopath | sort > "${DIR}/meta/filelist.tmp" || error "Failed to generate filelist.tmp"
    comm -13 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
        /usr/bin/fetch "${URL}/${_file}" -o "${DIR}/packages/All" || error "Failed to download new pkg ${URL}/${_file}"
    done
    comm -23 "/usr/local/pkg-mirror/meta/filelist" "${DIR}/meta/filelist.tmp" | while read _file; do
        rm -f "${DIR}/packages/All/${_file}" || error "Failed to delete ${DIR}/packages/All/${_file}"
    done
    mv "${DIR}/meta/filelist.tmp" "/usr/local/pkg-mirror/meta/filelist" || error "Failed to move filelist.tmp"
    log "Synced packages to ${DIR}"
    ;;
help|-h|-help)
    echo "Usage: pkg-mirror auto|clean"
    exit 1
    ;;
*)
    echo "Usage: pkg-mirror auto|clean"
    exit 1
    ;;
esac

exit 0

